{'delete_outputdir': True,
 'ignore_files': ['.#*'],
 'output_path': '/Users/ruiz/projects/mxxi/m-xxi.github.io',
 'output_retention': ['.git'],
 'path': '/Users/ruiz/projects/mxxi/src/content',
 'plugins': [<module 'keyword_related' from '/Users/ruiz/projects/mxxi/src/pelican-plugins/keyword_related.py'>,
             <module 'pelican-toc' from '/Users/ruiz/projects/mxxi/src/pelican-plugins/pelican-toc/__init__.py'>,
             <module 'tag_cloud-dict' from '/Users/ruiz/projects/mxxi/src/pelican-plugins/tag_cloud-dict.py'>,
             <module 'readtime' from '/Users/ruiz/projects/mxxi/src/pelican-plugins/readtime/__init__.py'>],
 'settings': {'ARCHIVES_SAVE_AS': '',
              'ARTICLE_EXCLUDES': ['scripta/versions', 'pages'],
              'ARTICLE_LANG_SAVE_AS': '',
              'ARTICLE_LANG_URL': '',
              'ARTICLE_ORDER_BY': 'reversed-date',
              'ARTICLE_PATHS': [''],
              'ARTICLE_PERMALINK_STRUCTURE': '',
              'ARTICLE_SAVE_AS': '{category}/{slug}/index.html',
              'ARTICLE_TRANSLATION_ID': 'fpath',
              'ARTICLE_URL': '{category}/{slug}',
              'AUTHOR': 'lea',
              'AUTHOR_FEED_ATOM': '',
              'AUTHOR_FEED_RSS': '',
              'AUTHOR_SAVE_AS': '',
              'AUTHOR_URL': 'author/{slug}.html',
              'BIND': '127.0.0.1',
              'CACHE_CONTENT': False,
              'CACHE_PATH': 'cache',
              'CATEGORY_FEED_ATOM': '',
              'CATEGORY_SAVE_AS': '',
              'CATEGORY_URL': '',
              'CHECK_MODIFIED_METHOD': 'mtime',
              'CODE': {'label': 'código', 'url': 'situs/codigo'},
              'CONTENT_CACHING_LAYER': 'reader',
              'COPYRIGHT': {'label': '©m-xxi2023', 'url': 'situs/info'},
              'CSS_FILE': 'main.css',
              'DATE_FORMATS': {'en': ('en_US', '%a, %d %b %Y'),
                               'es': ('es_ES', '%a, %d de %b %Y')},
              'DAY_ARCHIVE_SAVE_AS': '',
              'DAY_ARCHIVE_URL': '',
              'DEBUG': False,
              'DEFAULT_CATEGORY': '',
              'DEFAULT_DATE': 'fs',
              'DEFAULT_DATE_FORMAT': '%a %d %B %Y',
              'DEFAULT_LANG': 'es',
              'DEFAULT_METADATA': {},
              'DEFAULT_ORPHANS': 0,
              'DEFAULT_PAGINATION': False,
              'DELETE_OUTPUT_DIRECTORY': True,
              'DIRECT_TEMPLATES': ('index',),
              'DISPLAY_CATEGORIES_ON_MENU': True,
              'DISPLAY_PAGES_ON_MENU': True,
              'DOCUTILS_SETTINGS': {},
              'DRAFT_LANG_SAVE_AS': 'drafts/{slug}-{lang}.html',
              'DRAFT_LANG_URL': 'drafts/{slug}-{lang}.html',
              'DRAFT_PAGE_LANG_SAVE_AS': 'drafts/pages/{slug}-{lang}.html',
              'DRAFT_PAGE_LANG_URL': 'drafts/pages/{slug}-{lang}.html',
              'DRAFT_PAGE_SAVE_AS': 'drafts/pages/{slug}.html',
              'DRAFT_PAGE_URL': 'drafts/pages/{slug}.html',
              'DRAFT_SAVE_AS': 'drafts/{slug}.html',
              'DRAFT_URL': 'drafts/{slug}.html',
              'ENGLISH_LABELS': {'about': 'info',
                                 'author': 'author',
                                 'authors': 'authors',
                                 'bright': 'bright reading',
                                 'by': 'by',
                                 'calendar': 'calendar',
                                 'categories': 'categories',
                                 'category': 'category',
                                 'character': 'character',
                                 'clavis': 'clavis',
                                 'code': 'code',
                                 'dark': 'dark reading',
                                 'display': 'display',
                                 'filter': 'filter',
                                 'home': 'home',
                                 'lang': 'en',
                                 'languages': {'en': 'english',
                                               'es': 'spanish'},
                                 'less': 'less',
                                 'more': 'more',
                                 'plr': {'author': 'authors',
                                         'category': 'categories',
                                         'post': 'posts',
                                         'tag': 'tags',
                                         'type': 'type'},
                                 'post': 'scripta',
                                 'posts': 'scripta',
                                 'search': 'search',
                                 'sink': {'archive': 'archive',
                                          'archives': 'archives',
                                          'author': 'author',
                                          'authors': 'authors',
                                          'bottom': 'bottom',
                                          'bottoms': 'bottoms',
                                          'categories': 'categories',
                                          'category': 'category',
                                          'character': 'character',
                                          'characters': 'characters',
                                          'home': 'home',
                                          'homes': 'homes',
                                          'page': 'page',
                                          'pages': 'pages',
                                          'post': 'post',
                                          'posts': 'posts',
                                          'tag': 'tag',
                                          'tags': 'tags',
                                          'time': 'time',
                                          'times': 'times',
                                          'top': 'top',
                                          'tops': 'tops',
                                          'translation': 'translation',
                                          'translations': 'translations',
                                          'type': 'type',
                                          'version': 'version',
                                          'versions': 'versions'},
                                 'site': 'situs',
                                 'src': {'archive': 'archive',
                                         'archives': 'archives',
                                         'author': 'author',
                                         'authors': 'authors',
                                         'bottom': 'bottom',
                                         'bottoms': 'bottoms',
                                         'categories': 'categories',
                                         'category': 'category',
                                         'character': 'character',
                                         'characters': 'characters',
                                         'home': 'home',
                                         'homes': 'homes',
                                         'page': 'page',
                                         'pages': 'pages',
                                         'plr': {'author': 'authors',
                                                 'category': 'categories',
                                                 'post': 'posts',
                                                 'tag': 'tags',
                                                 'type': 'type'},
                                         'post': 'post',
                                         'posts': 'posts',
                                         'tag': 'tag',
                                         'tags': 'tags',
                                         'time': 'time',
                                         'times': 'times',
                                         'top': 'top',
                                         'tops': 'tops',
                                         'translation': 'translation',
                                         'translations': 'translations',
                                         'type': 'type',
                                         'version': 'version',
                                         'versions': 'versions'},
                                 'tag': 'tag',
                                 'tags': 'tags',
                                 'templates': {'archive': 'archive',
                                               'archives': 'archives',
                                               'author': 'author',
                                               'authors': 'authors',
                                               'bottom': 'bottom',
                                               'bottoms': 'bottoms',
                                               'categories': 'categories',
                                               'category': 'category',
                                               'character': 'character',
                                               'characters': 'characters',
                                               'home': 'home',
                                               'homes': 'homes',
                                               'page': 'page',
                                               'pages': 'pages',
                                               'post': 'post',
                                               'posts': 'posts',
                                               'tag': 'tag',
                                               'tags': 'tags',
                                               'time': 'time',
                                               'times': 'times',
                                               'top': 'top',
                                               'tops': 'tops',
                                               'translation': 'translation',
                                               'translations': 'translations',
                                               'type': 'type',
                                               'version': 'version',
                                               'versions': 'versions'},
                                 'toc': {'title': 'Table of Contents'},
                                 'translation': 'translation',
                                 'translations': 'translations',
                                 'type': 'type',
                                 'version': 'version',
                                 'versions': 'versions'},
              'EXTRA_PATH_METADATA': {},
              'FEED_ALL_ATOM': '',
              'FEED_DOMAIN': 'http://127.0.0.1:8001/.',
              'FEED_MAX_ITEMS': '',
              'FILENAME_METADATA': '(?P<title>.*)-(?P<lang>.*)',
              'FORMATTED_FIELDS': ['summary'],
              'GITHUB': {'project': 'project',
                         'url': 'm-xxi.github.io',
                         'user': 'm-xxi'},
              'GZIP_CACHE': True,
              'HTML': {'algolia_search': {'fname': '/includes/algolia.search.html',
                                          'name': 'algolia.search.html',
                                          'path': '/includes'},
                       'article': {'fname': 'article.html',
                                   'name': 'article.html',
                                   'path': ''},
                       'article_card': {'fname': '/layouts/partial/article-card.html',
                                        'name': 'article-card.html',
                                        'path': '/layouts/partial'},
                       'article_info': {'fname': '/layouts/partial/article-info.html',
                                        'name': 'article-info.html',
                                        'path': '/layouts/partial'},
                       'article_keyw': {'fname': '/layouts/partial/article-keyw.html',
                                        'name': 'article-keyw.html',
                                        'path': '/layouts/partial'},
                       'article_macro': {'fname': 'article_macro.html',
                                         'name': 'article_macro.html',
                                         'path': ''},
                       'article_tags': {'fname': '/layouts/partial/article-tags.html',
                                        'name': 'article-tags.html',
                                        'path': '/layouts/partial'},
                       'article_translations': {'fname': '/layouts/partial/article-translations.html',
                                                'name': 'article-translations.html',
                                                'path': '/layouts/partial'},
                       'articles': {'fname': '/layouts/partial/articles.html',
                                    'name': 'articles.html',
                                    'path': '/layouts/partial'},
                       'base': {'fname': '/layouts/base.html',
                                'name': 'base.html',
                                'path': '/layouts'},
                       'header': {'fname': '/includes/header.html',
                                  'name': 'header.html',
                                  'path': '/includes'},
                       'index': {'fname': 'index.html',
                                 'name': 'index.html',
                                 'path': ''},
                       'item_svg': {'fname': '/layouts/partial/item-svg.html',
                                    'name': 'item-svg.html',
                                    'path': '/layouts/partial'},
                       'keyw_clouds': {'fname': '/layouts/partial/keyw-clouds.html',
                                       'name': 'keyw-clouds.html',
                                       'path': '/layouts/partial'},
                       'landing': {'fname': 'landing.html',
                                   'name': 'landing.html',
                                   'path': ''},
                       'minimal': {'fname': '/layouts/minimal.html',
                                   'name': 'minimal.html',
                                   'path': '/layouts'},
                       'navbar': {'fname': '/layouts/navigation/navbar.html',
                                  'name': 'navbar.html',
                                  'path': '/layouts/navigation'},
                       'navbar_ul_li': {'fname': '/layouts/navigation/navbar.ul.li.html',
                                        'name': 'navbar.ul.li.html',
                                        'path': '/layouts/navigation'},
                       'pagination': {'fname': '/layouts/partial/pagination.html',
                                      'name': 'pagination.html',
                                      'path': '/layouts/partial'},
                       'related': {'fname': '/layouts/related.html',
                                   'name': 'related.html',
                                   'path': '/layouts'},
                       'scripts': {'fname': '/includes/scripts.html',
                                   'name': 'scripts.html',
                                   'path': '/includes'},
                       'search': {'fname': '/layouts/search.html',
                                  'name': 'search.html',
                                  'path': '/layouts'},
                       'sidenav': {'fname': '/layouts/navigation/sidenav.html',
                                   'name': 'sidenav.html',
                                   'path': '/layouts/navigation'},
                       'sidenav_conf': {'fname': '/layouts/navigation/sidenav.conf.html',
                                        'name': 'sidenav.conf.html',
                                        'path': '/layouts/navigation'},
                       'topnav': {'fname': '/layouts/navigation/topnav.html',
                                  'name': 'topnav.html',
                                  'path': '/layouts/navigation'},
                       'translations_funcs': {'fname': '/funcs/translations.html',
                                              'name': 'translations.html',
                                              'path': '/funcs'}},
              'ICON_DIR': 'static/icons',
              'IGNORE_FILES': ['.#*'],
              'INDEX_SAVE_AS': 'index.html',
              'INTRASITE_LINK_REGEX': '[{|](?P<what>.*?)[|}]',
              'JINJA_ENVIRONMENT': {'extensions': [],
                                    'lstrip_blocks': True,
                                    'trim_blocks': True},
              'JINJA_FILTERS': {},
              'JINJA_GLOBALS': {},
              'JINJA_TESTS': {},
              'KW_HASH': ['\\&', '#', '@'],
              'KW_TYPES': ['categories', 'tags', 'authors'],
              'KW_TYPES_SING': ['category', 'tag', 'author'],
              'LABELS': {'about': 'info',
                         'author': 'personaje',
                         'authors': 'personajes',
                         'bright': 'lectura diurna',
                         'by': 'x',
                         'calendar': 'calendario',
                         'categories': 'categorías',
                         'category': 'categoría',
                         'character': 'personaje',
                         'clavis': 'clavis',
                         'code': 'código',
                         'dark': 'lectura nocturna',
                         'display': 'contraste',
                         'filter': 'filtro',
                         'home': 'inicio',
                         'lang': 'es',
                         'languages': {'en': 'inglés', 'es': 'español'},
                         'less': 'menos',
                         'more': 'más',
                         'plr': {'author': 'personajes',
                                 'category': 'categorías',
                                 'post': 'escritos',
                                 'tag': 'tags',
                                 'type': 'tipo'},
                         'post': 'scripta',
                         'posts': 'scripta',
                         'search': 'buscar',
                         'sink': {'archive': 'archivo',
                                  'archives': 'archivos',
                                  'author': 'autor',
                                  'authors': 'autores',
                                  'bottom': 'abajo',
                                  'bottoms': 'abajo',
                                  'categories': 'categorías',
                                  'category': 'categoría',
                                  'character': 'personaje',
                                  'characters': 'personajes',
                                  'home': 'inicio',
                                  'homes': 'inicios',
                                  'page': 'página',
                                  'pages': 'páginas',
                                  'post': 'escrito',
                                  'posts': 'escritos',
                                  'tag': 'tag',
                                  'tags': 'tags',
                                  'time': 'tiempo',
                                  'times': 'tiempos',
                                  'top': 'arriba',
                                  'tops': 'arriba',
                                  'translation': 'traducción',
                                  'translations': 'traducciones',
                                  'type': 'tipo',
                                  'version': 'vesión',
                                  'versions': 'versiones'},
                         'site': 'situs',
                         'src': {'archive': 'archive',
                                 'archives': 'archives',
                                 'author': 'author',
                                 'authors': 'authors',
                                 'bottom': 'bottom',
                                 'bottoms': 'bottoms',
                                 'categories': 'categories',
                                 'category': 'category',
                                 'character': 'character',
                                 'characters': 'characters',
                                 'home': 'home',
                                 'homes': 'homes',
                                 'page': 'page',
                                 'pages': 'pages',
                                 'plr': {'author': 'authors',
                                         'category': 'categories',
                                         'post': 'posts',
                                         'tag': 'tags',
                                         'type': 'type'},
                                 'post': 'post',
                                 'posts': 'posts',
                                 'tag': 'tag',
                                 'tags': 'tags',
                                 'time': 'time',
                                 'times': 'times',
                                 'top': 'top',
                                 'tops': 'tops',
                                 'translation': 'translation',
                                 'translations': 'translations',
                                 'type': 'type',
                                 'version': 'version',
                                 'versions': 'versions'},
                         'tag': 'etiqueta',
                         'tags': 'etiquetas',
                         'templates': {'archive': 'archivo',
                                       'archives': 'archivos',
                                       'author': 'autor',
                                       'authors': 'autores',
                                       'bottom': 'abajo',
                                       'bottoms': 'abajo',
                                       'categories': 'categorías',
                                       'category': 'categoría',
                                       'character': 'personaje',
                                       'characters': 'personajes',
                                       'home': 'inicio',
                                       'homes': 'inicios',
                                       'page': 'página',
                                       'pages': 'páginas',
                                       'post': 'escrito',
                                       'posts': 'escritos',
                                       'tag': 'tag',
                                       'tags': 'tags',
                                       'time': 'tiempo',
                                       'times': 'tiempos',
                                       'top': 'arriba',
                                       'tops': 'arriba',
                                       'translation': 'traducción',
                                       'translations': 'traducciones',
                                       'type': 'tipo',
                                       'version': 'vesión',
                                       'versions': 'versiones'},
                         'toc': {'title': 'Índice'},
                         'translation': 'traducción',
                         'translations': 'tranducciones',
                         'type': 'tipo',
                         'version': 'versión',
                         'versions': 'versiones'},
              'LANDING_PATH': 'M-XXI',
              'LANG_DIR': '.',
              'LIST2DICT': <function LIST2DICT at 0x7fac2ecd1e50>,
              'LOAD_CONTENT_CACHE': False,
              'LOCALE': [''],
              'LOG_FILTER': [],
              'MARKDOWN': {'extension_configs': {'markdown.extensions.admonition': {},
                                                 'markdown.extensions.codehilite': {'css_class': 'highlight'},
                                                 'markdown.extensions.extra': {},
                                                 'markdown.extensions.meta': {},
                                                 'markdown.extensions.toc': {'toc_class': 'toc',
                                                                             'toc_depth': '2-4'},
                                                 'mdx_include': {'base_path': '/Users/ruiz/projects/mxxi/src/content',
                                                                 'recurs_local': True}},
                           'extensions': ['mdx_include',
                                          'markdown.extensions.codehilite',
                                          'markdown.extensions.extra',
                                          'markdown.extensions.meta',
                                          'markdown.extensions.admonition',
                                          'markdown.extensions.toc'],
                           'output_format': 'html5'},
              'MONTH_ARCHIVE_SAVE_AS': '',
              'MONTH_ARCHIVE_URL': '',
              'MULTI_LANG_LABELS': {'en': {'about': 'info',
                                           'author': 'author',
                                           'authors': 'authors',
                                           'bright': 'bright reading',
                                           'by': 'by',
                                           'calendar': 'calendar',
                                           'categories': 'categories',
                                           'category': 'category',
                                           'character': 'character',
                                           'clavis': 'clavis',
                                           'code': 'code',
                                           'dark': 'dark reading',
                                           'display': 'display',
                                           'filter': 'filter',
                                           'home': 'home',
                                           'lang': 'en',
                                           'languages': {'en': 'english',
                                                         'es': 'spanish'},
                                           'less': 'less',
                                           'more': 'more',
                                           'plr': {'author': 'authors',
                                                   'category': 'categories',
                                                   'post': 'posts',
                                                   'tag': 'tags',
                                                   'type': 'type'},
                                           'post': 'scripta',
                                           'posts': 'scripta',
                                           'search': 'search',
                                           'sink': {'archive': 'archive',
                                                    'archives': 'archives',
                                                    'author': 'author',
                                                    'authors': 'authors',
                                                    'bottom': 'bottom',
                                                    'bottoms': 'bottoms',
                                                    'categories': 'categories',
                                                    'category': 'category',
                                                    'character': 'character',
                                                    'characters': 'characters',
                                                    'home': 'home',
                                                    'homes': 'homes',
                                                    'page': 'page',
                                                    'pages': 'pages',
                                                    'post': 'post',
                                                    'posts': 'posts',
                                                    'tag': 'tag',
                                                    'tags': 'tags',
                                                    'time': 'time',
                                                    'times': 'times',
                                                    'top': 'top',
                                                    'tops': 'tops',
                                                    'translation': 'translation',
                                                    'translations': 'translations',
                                                    'type': 'type',
                                                    'version': 'version',
                                                    'versions': 'versions'},
                                           'site': 'situs',
                                           'src': {'archive': 'archive',
                                                   'archives': 'archives',
                                                   'author': 'author',
                                                   'authors': 'authors',
                                                   'bottom': 'bottom',
                                                   'bottoms': 'bottoms',
                                                   'categories': 'categories',
                                                   'category': 'category',
                                                   'character': 'character',
                                                   'characters': 'characters',
                                                   'home': 'home',
                                                   'homes': 'homes',
                                                   'page': 'page',
                                                   'pages': 'pages',
                                                   'plr': {'author': 'authors',
                                                           'category': 'categories',
                                                           'post': 'posts',
                                                           'tag': 'tags',
                                                           'type': 'type'},
                                                   'post': 'post',
                                                   'posts': 'posts',
                                                   'tag': 'tag',
                                                   'tags': 'tags',
                                                   'time': 'time',
                                                   'times': 'times',
                                                   'top': 'top',
                                                   'tops': 'tops',
                                                   'translation': 'translation',
                                                   'translations': 'translations',
                                                   'type': 'type',
                                                   'version': 'version',
                                                   'versions': 'versions'},
                                           'tag': 'tag',
                                           'tags': 'tags',
                                           'templates': {'archive': 'archive',
                                                         'archives': 'archives',
                                                         'author': 'author',
                                                         'authors': 'authors',
                                                         'bottom': 'bottom',
                                                         'bottoms': 'bottoms',
                                                         'categories': 'categories',
                                                         'category': 'category',
                                                         'character': 'character',
                                                         'characters': 'characters',
                                                         'home': 'home',
                                                         'homes': 'homes',
                                                         'page': 'page',
                                                         'pages': 'pages',
                                                         'post': 'post',
                                                         'posts': 'posts',
                                                         'tag': 'tag',
                                                         'tags': 'tags',
                                                         'time': 'time',
                                                         'times': 'times',
                                                         'top': 'top',
                                                         'tops': 'tops',
                                                         'translation': 'translation',
                                                         'translations': 'translations',
                                                         'type': 'type',
                                                         'version': 'version',
                                                         'versions': 'versions'},
                                           'toc': {'title': 'Table of '
                                                            'Contents'},
                                           'translation': 'translation',
                                           'translations': 'translations',
                                           'type': 'type',
                                           'version': 'version',
                                           'versions': 'versions'},
                                    'es': {'about': 'info',
                                           'author': 'personaje',
                                           'authors': 'personajes',
                                           'bright': 'lectura diurna',
                                           'by': 'x',
                                           'calendar': 'calendario',
                                           'categories': 'categorías',
                                           'category': 'categoría',
                                           'character': 'personaje',
                                           'clavis': 'clavis',
                                           'code': 'código',
                                           'dark': 'lectura nocturna',
                                           'display': 'contraste',
                                           'filter': 'filtro',
                                           'home': 'inicio',
                                           'lang': 'es',
                                           'languages': {'en': 'inglés',
                                                         'es': 'español'},
                                           'less': 'menos',
                                           'more': 'más',
                                           'plr': {'author': 'personajes',
                                                   'category': 'categorías',
                                                   'post': 'escritos',
                                                   'tag': 'tags',
                                                   'type': 'tipo'},
                                           'post': 'scripta',
                                           'posts': 'scripta',
                                           'search': 'buscar',
                                           'sink': {'archive': 'archivo',
                                                    'archives': 'archivos',
                                                    'author': 'autor',
                                                    'authors': 'autores',
                                                    'bottom': 'abajo',
                                                    'bottoms': 'abajo',
                                                    'categories': 'categorías',
                                                    'category': 'categoría',
                                                    'character': 'personaje',
                                                    'characters': 'personajes',
                                                    'home': 'inicio',
                                                    'homes': 'inicios',
                                                    'page': 'página',
                                                    'pages': 'páginas',
                                                    'post': 'escrito',
                                                    'posts': 'escritos',
                                                    'tag': 'tag',
                                                    'tags': 'tags',
                                                    'time': 'tiempo',
                                                    'times': 'tiempos',
                                                    'top': 'arriba',
                                                    'tops': 'arriba',
                                                    'translation': 'traducción',
                                                    'translations': 'traducciones',
                                                    'type': 'tipo',
                                                    'version': 'vesión',
                                                    'versions': 'versiones'},
                                           'site': 'situs',
                                           'src': {'archive': 'archive',
                                                   'archives': 'archives',
                                                   'author': 'author',
                                                   'authors': 'authors',
                                                   'bottom': 'bottom',
                                                   'bottoms': 'bottoms',
                                                   'categories': 'categories',
                                                   'category': 'category',
                                                   'character': 'character',
                                                   'characters': 'characters',
                                                   'home': 'home',
                                                   'homes': 'homes',
                                                   'page': 'page',
                                                   'pages': 'pages',
                                                   'plr': {'author': 'authors',
                                                           'category': 'categories',
                                                           'post': 'posts',
                                                           'tag': 'tags',
                                                           'type': 'type'},
                                                   'post': 'post',
                                                   'posts': 'posts',
                                                   'tag': 'tag',
                                                   'tags': 'tags',
                                                   'time': 'time',
                                                   'times': 'times',
                                                   'top': 'top',
                                                   'tops': 'tops',
                                                   'translation': 'translation',
                                                   'translations': 'translations',
                                                   'type': 'type',
                                                   'version': 'version',
                                                   'versions': 'versions'},
                                           'tag': 'etiqueta',
                                           'tags': 'etiquetas',
                                           'templates': {'archive': 'archivo',
                                                         'archives': 'archivos',
                                                         'author': 'autor',
                                                         'authors': 'autores',
                                                         'bottom': 'abajo',
                                                         'bottoms': 'abajo',
                                                         'categories': 'categorías',
                                                         'category': 'categoría',
                                                         'character': 'personaje',
                                                         'characters': 'personajes',
                                                         'home': 'inicio',
                                                         'homes': 'inicios',
                                                         'page': 'página',
                                                         'pages': 'páginas',
                                                         'post': 'escrito',
                                                         'posts': 'escritos',
                                                         'tag': 'tag',
                                                         'tags': 'tags',
                                                         'time': 'tiempo',
                                                         'times': 'tiempos',
                                                         'top': 'arriba',
                                                         'tops': 'arriba',
                                                         'translation': 'traducción',
                                                         'translations': 'traducciones',
                                                         'type': 'tipo',
                                                         'version': 'vesión',
                                                         'versions': 'versiones'},
                                           'toc': {'title': 'Índice'},
                                           'translation': 'traducción',
                                           'translations': 'tranducciones',
                                           'type': 'tipo',
                                           'version': 'versión',
                                           'versions': 'versiones'}},
              'MULTI_SITE': False,
              'MULTI_SITE_DIR': '.',
              'NEWEST_FIRST_ARCHIVES': True,
              'OUTPUT_PATH': '/Users/ruiz/projects/mxxi/m-xxi.github.io',
              'OUTPUT_RETENTION': ['.git'],
              'OUTPUT_SOURCES': False,
              'OUTPUT_SOURCES_EXTENSION': '.text',
              'PAGE_EXCLUDES': [''],
              'PAGE_LANG_SAVE_AS': '',
              'PAGE_LANG_URL': '',
              'PAGE_ORDER_BY': 'basename',
              'PAGE_PATHS': ['pages'],
              'PAGE_SAVE_AS': '',
              'PAGE_TRANSLATION_ID': 'slug',
              'PAGE_URL': 'pages/{slug}.html',
              'PAGINATED_TEMPLATES': {'author': None,
                                      'category': None,
                                      'index': None,
                                      'tag': None},
              'PAGINATION_PATTERNS': [PaginationRule(min_page=1, URL='{name}{extension}', SAVE_AS='{name}{extension}'),
                                      PaginationRule(min_page=2, URL='{name}{number}{extension}', SAVE_AS='{name}{number}{extension}')],
              'PATH': '/Users/ruiz/projects/mxxi/src/content',
              'PATH_METADATA': '(?P<category>.*?)/(?P<fpath>.*)/.*',
              'PELICAN_CLASS': 'pelican.Pelican',
              'PLUGINS': ['keyword_related',
                          'pelican-toc',
                          'tag_cloud-dict',
                          'readtime'],
              'PLUGIN_PATHS': ['/Users/ruiz/projects/mxxi/src/pelican-plugins'],
              'PLURALIZE': <function PLURALIZE at 0x7fac2eaaa3a0>,
              'PLURAL_TEMPLATES': ['type',
                                   'tags',
                                   'categories',
                                   'archives',
                                   'authors',
                                   'posts',
                                   'characters',
                                   'homes',
                                   'times',
                                   'translations',
                                   'pages',
                                   'tops',
                                   'bottoms',
                                   'versions'],
              'PLURAL_TEMPLATES_ES': ['tipo',
                                      'tags',
                                      'categorías',
                                      'archivos',
                                      'autores',
                                      'escritos',
                                      'personajes',
                                      'inicios',
                                      'tiempos',
                                      'traducciones',
                                      'páginas',
                                      'arriba',
                                      'abajo',
                                      'versiones'],
              'PORT': 8001,
              'PUBLISH': None,
              'PYGMENTS_RST_OPTIONS': {},
              'READERS': {},
              'RELATIVE_URLS': False,
              'REL_TO_CONFIG_PATH': '../',
              'REVERSE_CATEGORY_ORDER': False,
              'RSS_FEED_SUMMARY_ONLY': True,
              'SAVE_AS': {},
              'SEARCH_HTML_SELECTOR': 'main',
              'SEARCH_MODE': 'output',
              'SINGULAR_TEMPLATES': ['type',
                                     'tag',
                                     'category',
                                     'archive',
                                     'author',
                                     'post',
                                     'character',
                                     'home',
                                     'time',
                                     'translation',
                                     'page',
                                     'top',
                                     'bottom',
                                     'version'],
              'SINGULAR_TEMPLATES_ES': ['tipo',
                                        'tag',
                                        'categoría',
                                        'archivo',
                                        'autor',
                                        'escrito',
                                        'personaje',
                                        'inicio',
                                        'tiempo',
                                        'traducción',
                                        'página',
                                        'arriba',
                                        'abajo',
                                        'vesión'],
              'SITENAME': 'M-XXI',
              'SITEURL': 'http://127.0.0.1:8001/.',
              'SLUGIFY_PRESERVE_CASE': False,
              'SLUGIFY_SOURCE': 'title',
              'SLUGIFY_USE_UNICODE': False,
              'SLUG_REGEX_SUBSTITUTIONS': [('[^\\w\\s-]', ''),
                                           ('(?u)\\A\\s*', ''),
                                           ('(?u)\\s*\\Z', ''),
                                           ('[-\\s]+', '-')],
              'SPANISH_LABELS': {'about': 'info',
                                 'author': 'personaje',
                                 'authors': 'personajes',
                                 'bright': 'lectura diurna',
                                 'by': 'x',
                                 'calendar': 'calendario',
                                 'categories': 'categorías',
                                 'category': 'categoría',
                                 'character': 'personaje',
                                 'clavis': 'clavis',
                                 'code': 'código',
                                 'dark': 'lectura nocturna',
                                 'display': 'contraste',
                                 'filter': 'filtro',
                                 'home': 'inicio',
                                 'lang': 'es',
                                 'languages': {'en': 'inglés', 'es': 'español'},
                                 'less': 'menos',
                                 'more': 'más',
                                 'plr': {'author': 'personajes',
                                         'category': 'categorías',
                                         'post': 'escritos',
                                         'tag': 'tags',
                                         'type': 'tipo'},
                                 'post': 'scripta',
                                 'posts': 'scripta',
                                 'search': 'buscar',
                                 'sink': {'archive': 'archivo',
                                          'archives': 'archivos',
                                          'author': 'autor',
                                          'authors': 'autores',
                                          'bottom': 'abajo',
                                          'bottoms': 'abajo',
                                          'categories': 'categorías',
                                          'category': 'categoría',
                                          'character': 'personaje',
                                          'characters': 'personajes',
                                          'home': 'inicio',
                                          'homes': 'inicios',
                                          'page': 'página',
                                          'pages': 'páginas',
                                          'post': 'escrito',
                                          'posts': 'escritos',
                                          'tag': 'tag',
                                          'tags': 'tags',
                                          'time': 'tiempo',
                                          'times': 'tiempos',
                                          'top': 'arriba',
                                          'tops': 'arriba',
                                          'translation': 'traducción',
                                          'translations': 'traducciones',
                                          'type': 'tipo',
                                          'version': 'vesión',
                                          'versions': 'versiones'},
                                 'site': 'situs',
                                 'src': {'archive': 'archive',
                                         'archives': 'archives',
                                         'author': 'author',
                                         'authors': 'authors',
                                         'bottom': 'bottom',
                                         'bottoms': 'bottoms',
                                         'categories': 'categories',
                                         'category': 'category',
                                         'character': 'character',
                                         'characters': 'characters',
                                         'home': 'home',
                                         'homes': 'homes',
                                         'page': 'page',
                                         'pages': 'pages',
                                         'plr': {'author': 'authors',
                                                 'category': 'categories',
                                                 'post': 'posts',
                                                 'tag': 'tags',
                                                 'type': 'type'},
                                         'post': 'post',
                                         'posts': 'posts',
                                         'tag': 'tag',
                                         'tags': 'tags',
                                         'time': 'time',
                                         'times': 'times',
                                         'top': 'top',
                                         'tops': 'tops',
                                         'translation': 'translation',
                                         'translations': 'translations',
                                         'type': 'type',
                                         'version': 'version',
                                         'versions': 'versions'},
                                 'tag': 'etiqueta',
                                 'tags': 'etiquetas',
                                 'templates': {'archive': 'archivo',
                                               'archives': 'archivos',
                                               'author': 'autor',
                                               'authors': 'autores',
                                               'bottom': 'abajo',
                                               'bottoms': 'abajo',
                                               'categories': 'categorías',
                                               'category': 'categoría',
                                               'character': 'personaje',
                                               'characters': 'personajes',
                                               'home': 'inicio',
                                               'homes': 'inicios',
                                               'page': 'página',
                                               'pages': 'páginas',
                                               'post': 'escrito',
                                               'posts': 'escritos',
                                               'tag': 'tag',
                                               'tags': 'tags',
                                               'time': 'tiempo',
                                               'times': 'tiempos',
                                               'top': 'arriba',
                                               'tops': 'arriba',
                                               'translation': 'traducción',
                                               'translations': 'traducciones',
                                               'type': 'tipo',
                                               'version': 'vesión',
                                               'versions': 'versiones'},
                                 'toc': {'title': 'Índice'},
                                 'translation': 'traducción',
                                 'translations': 'tranducciones',
                                 'type': 'tipo',
                                 'version': 'versión',
                                 'versions': 'versiones'},
              'STATIC_CHECK_IF_MODIFIED': False,
              'STATIC_CREATE_LINKS': False,
              'STATIC_EXCLUDES': [],
              'STATIC_EXCLUDE_SOURCES': True,
              'STATIC_LANG_SAVE_AS': '{path}',
              'STATIC_PATHS': ['static/images', 'static/icons'],
              'STATIC_SAVE_AS': '{path}',
              'STATIC_URL': '{path}',
              'SUBTEXT': 'un recurso precursor a la excursión incursiva',
              'SUBTITLE': '<mxxi>Manuscrito XXI</mxxi>',
              'SUMMARY_END_SUFFIX': '…',
              'SUMMARY_MAX_LENGTH': 50,
              'TAG_CLOUD_BADGE': False,
              'TAG_CLOUD_MAX_ITEMS': 100,
              'TAG_CLOUD_SORTING': 'size',
              'TAG_CLOUD_STEPS': 4,
              'TAG_SAVE_AS': '',
              'TAG_URL': '',
              'TEMPLATES_ENGLISH': {'all': {'archive': 'archive',
                                            'archives': 'archives',
                                            'author': 'author',
                                            'authors': 'authors',
                                            'bottom': 'bottom',
                                            'bottoms': 'bottoms',
                                            'categories': 'categories',
                                            'category': 'category',
                                            'character': 'character',
                                            'characters': 'characters',
                                            'home': 'home',
                                            'homes': 'homes',
                                            'page': 'page',
                                            'pages': 'pages',
                                            'post': 'post',
                                            'posts': 'posts',
                                            'tag': 'tag',
                                            'tags': 'tags',
                                            'time': 'time',
                                            'times': 'times',
                                            'top': 'top',
                                            'tops': 'tops',
                                            'translation': 'translation',
                                            'translations': 'translations',
                                            'type': 'type',
                                            'version': 'version',
                                            'versions': 'versions'},
                                    'plr': {'archives': 'archives',
                                            'authors': 'authors',
                                            'bottoms': 'bottoms',
                                            'categories': 'categories',
                                            'characters': 'characters',
                                            'homes': 'homes',
                                            'pages': 'pages',
                                            'posts': 'posts',
                                            'tags': 'tags',
                                            'times': 'times',
                                            'tops': 'tops',
                                            'translations': 'translations',
                                            'type': 'type',
                                            'versions': 'versions'},
                                    'sing': {'archive': 'archive',
                                             'author': 'author',
                                             'bottom': 'bottom',
                                             'category': 'category',
                                             'character': 'character',
                                             'home': 'home',
                                             'page': 'page',
                                             'post': 'post',
                                             'tag': 'tag',
                                             'time': 'time',
                                             'top': 'top',
                                             'translation': 'translation',
                                             'type': 'type',
                                             'version': 'version'}},
              'TEMPLATES_SPANISH': {'all': {'archive': 'archivo',
                                            'archives': 'archivos',
                                            'author': 'autor',
                                            'authors': 'autores',
                                            'bottom': 'abajo',
                                            'bottoms': 'abajo',
                                            'categories': 'categorías',
                                            'category': 'categoría',
                                            'character': 'personaje',
                                            'characters': 'personajes',
                                            'home': 'inicio',
                                            'homes': 'inicios',
                                            'page': 'página',
                                            'pages': 'páginas',
                                            'post': 'escrito',
                                            'posts': 'escritos',
                                            'tag': 'tag',
                                            'tags': 'tags',
                                            'time': 'tiempo',
                                            'times': 'tiempos',
                                            'top': 'arriba',
                                            'tops': 'arriba',
                                            'translation': 'traducción',
                                            'translations': 'traducciones',
                                            'type': 'tipo',
                                            'version': 'vesión',
                                            'versions': 'versiones'},
                                    'plr': {'archives': 'archivos',
                                            'authors': 'autores',
                                            'bottoms': 'abajo',
                                            'categories': 'categorías',
                                            'characters': 'personajes',
                                            'homes': 'inicios',
                                            'pages': 'páginas',
                                            'posts': 'escritos',
                                            'tags': 'tags',
                                            'times': 'tiempos',
                                            'tops': 'arriba',
                                            'translations': 'traducciones',
                                            'type': 'tipo',
                                            'versions': 'versiones'},
                                    'sing': {'archive': 'archivo',
                                             'author': 'autor',
                                             'bottom': 'abajo',
                                             'category': 'categoría',
                                             'character': 'personaje',
                                             'home': 'inicio',
                                             'page': 'página',
                                             'post': 'escrito',
                                             'tag': 'tag',
                                             'time': 'tiempo',
                                             'top': 'arriba',
                                             'translation': 'traducción',
                                             'type': 'tipo',
                                             'version': 'vesión'}},
              'TEMPLATE_EXTENSIONS': ['.html'],
              'TEMPLATE_PAGES': {},
              'THEME': '/Users/ruiz/projects/mxxi/src/themes/only-art-all-filter',
              'THEME_NAME': 'only-art-all-filter',
              'THEME_STATIC_DIR': 'static/theme',
              'THEME_STATIC_PATHS': ['static'],
              'THEME_TEMPLATES_OVERRIDES': [],
              'TIMEZONE': 'America/Argentina/Buenos_Aires',
              'TITLE': '<mxxi>Manuscrito XXI</mxxi>',
              'TOC': {'TOC_HEADERS': '^h[1-1]',
                      'TOC_INCLUDE_TITLE': 'false',
                      'TOC_RUN': 'true'},
              'TRANSLATION_FEED_ATOM': '',
              'TYPOGRIFY': True,
              'TYPOGRIFY_DASHES': 'default',
              'TYPOGRIFY_IGNORE_TAGS': [],
              'URLS': {'bottom': '#abajo', 'top': '#'},
              'USER': 'm-xxi',
              'USE_FOLDER_AS_CATEGORY': False,
              'WITH_FUTURE_DATES': True,
              'WRITE_SELECTED': [],
              'YEAR_ARCHIVE_SAVE_AS': '',
              'YEAR_ARCHIVE_URL': ''},
 'theme': '/Users/ruiz/projects/mxxi/src/themes/only-art-all-filter'}
Done: Processed 23 articles, 0 drafts, 1 hidden article, 0 pages, 0 hidden pages and 0 draft pages in 1.17 seconds.
